"""Pydantic models for the Vision-Reward-OS API.

This module defines the request and response schemas used by the
/evaluate/ab-test endpoint and related routes.
"""

from typing import Optional

from pydantic import BaseModel, Field, field_validator


class InputImages(BaseModel):
    """Request payload for an A/B image evaluation.

    Exactly one of ``image_a_url`` / ``image_a_b64`` must be provided for each
    image slot.  URL-based inputs are preferred for large payloads to keep
    request sizes small.

    Attributes:
        image_a_url: Publicly accessible URL of the first candidate image.
        image_a_b64: Base-64 encoded string of the first candidate image
            (alternative to ``image_a_url``).
        image_b_url: Publicly accessible URL of the second candidate image.
        image_b_b64: Base-64 encoded string of the second candidate image
            (alternative to ``image_b_url``).
        prompt: The text prompt that was used to generate both images.  Used
            by prompt-alignment evaluators (e.g. HPS, ImageReward).
    """

    image_a_url: Optional[str] = Field(
        default=None,
        description="Publicly accessible URL of candidate image A.",
        examples=["https://example.com/image_a.jpg"],
    )
    image_a_b64: Optional[str] = Field(
        default=None,
        description="Base-64 encoded bytes of candidate image A.",
    )
    image_b_url: Optional[str] = Field(
        default=None,
        description="Publicly accessible URL of candidate image B.",
        examples=["https://example.com/image_b.jpg"],
    )
    image_b_b64: Optional[str] = Field(
        default=None,
        description="Base-64 encoded bytes of candidate image B.",
    )
    prompt: Optional[str] = Field(
        default=None,
        description="Text prompt used to generate the images.",
        examples=["a cat sitting on a red couch"],
    )

    @field_validator("image_a_url", "image_b_url", mode="before")
    @classmethod
    def validate_url_scheme(cls, value: Optional[str]) -> Optional[str]:
        """Ensure image URLs use http or https."""
        if value is not None and not value.startswith(("http://", "https://")):
            raise ValueError("Image URLs must start with 'http://' or 'https://'.")
        return value


class EvaluatorScore(BaseModel):
    """Score produced by a single evaluator for one candidate image.

    Attributes:
        evaluator_name: Human-readable name of the evaluator (e.g. "PickScore").
        score_a: Raw score assigned to image A by this evaluator.
        score_b: Raw score assigned to image B by this evaluator.
        preferred: Which image this evaluator prefers (``"A"`` or ``"B"``).
        confidence: Confidence of the preference decision in the range [0, 1].
    """

    evaluator_name: str = Field(description="Name of the evaluator model.")
    score_a: float = Field(description="Raw score for image A.")
    score_b: float = Field(description="Raw score for image B.")
    preferred: str = Field(
        description="The preferred image: 'A' or 'B'.",
        pattern="^[AB]$",
    )
    confidence: float = Field(
        description="Confidence of the preference in the range [0, 1].",
        ge=0.0,
        le=1.0,
    )


class MultiDimensionalReport(BaseModel):
    """Aggregated multi-evaluator report for an A/B image comparison.

    Attributes:
        overall_winner: The image (``"A"`` or ``"B"``) preferred by the
            weighted majority of evaluators.
        overall_confidence: Aggregate confidence score across all evaluators,
            in the range [0, 1].
        evaluator_scores: Per-evaluator breakdown of individual scores and
            preferences.
        reasoning_summary: Optional natural-language summary generated by a
            VLM judge explaining the overall verdict.
        prompt_used: The text prompt that was supplied with the request (if
            any), echoed back for traceability.
    """

    overall_winner: str = Field(
        description="The overall preferred image: 'A' or 'B'.",
        pattern="^[AB]$",
    )
    overall_confidence: float = Field(
        description="Aggregate confidence across all evaluators, in [0, 1].",
        ge=0.0,
        le=1.0,
    )
    evaluator_scores: list[EvaluatorScore] = Field(
        description="Per-evaluator score breakdown.",
    )
    reasoning_summary: Optional[str] = Field(
        default=None,
        description="Natural-language explanation from the VLM judge.",
    )
    prompt_used: Optional[str] = Field(
        default=None,
        description="The text prompt supplied with the request, if any.",
    )
